// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJPUtkB820cm2K5VXVg1C9E6I17bnCATU',
    appId: '1:66143386752:web:7ed90d61ee631d92967a65',
    messagingSenderId: '66143386752',
    projectId: 'cert-5fc2d',
    authDomain: 'cert-5fc2d.firebaseapp.com',
    storageBucket: 'cert-5fc2d.firebasestorage.app',
    measurementId: 'G-E8LKJZ937P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdJ-yN5MEmMBoE0Cw9dhfEEftEvUFUMIM',
    appId: '1:66143386752:android:6e3beffe528c9b13967a65',
    messagingSenderId: '66143386752',
    projectId: 'cert-5fc2d',
    storageBucket: 'cert-5fc2d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQUEEeb_7gzkg1CUG0eaH2-RplC6nwCdQ',
    appId: '1:66143386752:ios:8051ebbafc32a24e967a65',
    messagingSenderId: '66143386752',
    projectId: 'cert-5fc2d',
    storageBucket: 'cert-5fc2d.firebasestorage.app',
    iosBundleId: 'com.example.cert1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQUEEeb_7gzkg1CUG0eaH2-RplC6nwCdQ',
    appId: '1:66143386752:ios:8051ebbafc32a24e967a65',
    messagingSenderId: '66143386752',
    projectId: 'cert-5fc2d',
    storageBucket: 'cert-5fc2d.firebasestorage.app',
    iosBundleId: 'com.example.cert1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJPUtkB820cm2K5VXVg1C9E6I17bnCATU',
    appId: '1:66143386752:web:dcdd191eafe95fc7967a65',
    messagingSenderId: '66143386752',
    projectId: 'cert-5fc2d',
    authDomain: 'cert-5fc2d.firebaseapp.com',
    storageBucket: 'cert-5fc2d.firebasestorage.app',
    measurementId: 'G-G62YZX76H5',
  );
}
